# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    e:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.gen/sources_1/bd/design_1/ipshared/ec67/hdl
    E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/ip/ila_0
    E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/ip/ila_1
    E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/ip/ila_2
    e:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/ip/fifo_generator_0
  } {
      F:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      F:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    e:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.gen/sources_1/bd/design_1/ipshared/ec67/hdl
    E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/ip/ila_0
    E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/ip/ila_1
    E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/ip/ila_2
    e:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/ip/fifo_generator_0
  } {
      E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/realtime/design_1_proc_sys_reset_0_0_stub.v
      E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/realtime/design_1_processing_system7_0_0_stub.v
      E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/realtime/design_1_axi_uart16550_0_1_stub.v
      E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/realtime/design_1_auto_pc_0_stub.v
      E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/realtime/ila_0_stub.v
      E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/realtime/ila_1_stub.v
      E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/realtime/ila_2_stub.v
      E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/realtime/fifo_generator_0_stub.v
      e:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.gen/sources_1/bd/design_1/synth/design_1.v
      E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
      E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/new/spi_process.v
      E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/new/spi_receive.v
      E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/new/spi_send.v
      E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.srcs/sources_1/new/IS_PTC_top.v
    }
      rt::read_vhdl -lib xpm F:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top IS_PTC_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/ZynqSpi_Demo/prj11_autofocus/.Xil/Vivado-19288-huiyi/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
