@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Aug 29 16:52:05 +0800 2024
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_spi_process_behav -key {Behavioral:sim_1:Functional:tb_spi_process} -tclbatch tb_spi_process.tcl -protoinst "protoinst_files/design_1.protoinst" -view E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.sim/tb_spi_process_behav.wcfg -log simulate.log"
call xsim  tb_spi_process_behav -key {Behavioral:sim_1:Functional:tb_spi_process} -tclbatch tb_spi_process.tcl -protoinst "protoinst_files/design_1.protoinst" -view E:/ZynqSpi_Demo/prj11_autofocus/01_app_hyis_ptc0808.sim/tb_spi_process_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
